apps/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
   path('', views.view_cart, name='view_cart'),
   path('update_item/<int:item_id>/', views.update_item, name='update_item'),
   path('remove_item/<int:item_id>/', views.remove_item, name='remove_item'),
   path('checkout/', views.checkout, name='checkout'),
]

apps/wishlist/urls.py
from django.urls import path
from .views import ViewWishListItem, ViewWishListAdd, ViewWishListDel

app_name = 'wishlist'

urlpatterns = [
    path('', ViewWishListItem.as_view(), name='wishlist'),
    path('add_wishlist/<int:product_id>', ViewWishListAdd.as_view(), name='add_to_wishlist'),
    path('del_wishlist/<int:item_id>', ViewWishListDel.as_view(), name='del_from_wishlist'),

]

common/urls.py
from django.urls import path

from .views import CurrentDateView

urlpatterns = [
   path('datetime/', CurrentDateView.as_view()),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

from apps.cart_shop.urls import router as cart_router



urlpatterns = [
   path('admin/', admin.site.urls),
   path('other/cart/', include('apps.cart.urls')),
   path('other/', include('apps.common.urls')),
   path('login/', include('apps.login.urls')),
   path('other/', include('apps.login.urls')),
   path('', include('apps.home.urls')),
   path('', include(cart_router.urls)),
   path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
   path('cart/', include('apps.cart_shop.urls')),
   path('login/', include('apps.auth_shop.urls')),
   path('wislist/', include('apps.wishlist.urls')),
   path('api/', include(cart_router.urls)),
]

apps/cart/models.py
from django.db import models


# Create your models here.


from django.db import models

from django.contrib.auth.models import User

from PIL import Image #Библиотека требует версию

class Cart(models.Model):
   user = models.ForeignKey(User, on_delete=models.CASCADE)
   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now=True)

   def __str__(self):
       return f"{self.user}"


class Product(models.Model):
   name = models.CharField(max_length=255)
   price = models.DecimalField(max_digits=10, decimal_places=2)
   description = models.TextField()
   image = models.ImageField(upload_to='static/products/', null=True, blank=True, default='products/')
   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now=True)

   def save(self, *args, **kwargs):
      super().save(*args, **kwargs)

      img = Image.open(self.image.path)
      img = img.resize((100, 100), Image.ANTIALIAS)
      img.save(self.image.path)


   def __str__(self):
       return self.name


class CartItem(models.Model):
   cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
   product = models.ForeignKey(Product, on_delete=models.CASCADE)
   quantity = models.IntegerField(default=1)
   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now=True)

   def __str__(self):
       return f"{self.cart}_{self.product}"

apps/wishlist/models.py
from django.db import models
from apps.cart.models import Cart
from apps.cart_shop.models import Product

class ViewWishListItem(models.Model):
   wishlist = models.ForeignKey(Cart, on_delete=models.CASCADE)
   product = models.ForeignKey(Product, on_delete=models.CASCADE)
   #quantity = models.IntegerField(default=1)
   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now=True)

   def __repr__(self):
      return f"{self.wishlist}_{self.product}"

cart/models.py
from django.db import models


# Create your models here.


from django.db import models

from django.contrib.auth.models import User


class Cart(models.Model):
   user = models.ForeignKey(User, on_delete=models.CASCADE)
   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now=True)

   def __str__(self):
       return f"{self.user}"


class Product(models.Model):
   name = models.CharField(max_length=255)
   price = models.DecimalField(max_digits=10, decimal_places=2)
   description = models.TextField()
   image = models.ImageField(upload_to='products/', null=True, blank=True, default='products/')
   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now=True)

   def __str__(self):
       return self.name


class CartItem(models.Model):
   cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
   product = models.ForeignKey(Product, on_delete=models.CASCADE)
   quantity = models.IntegerField(default=1)
   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now=True)

   def __str__(self):
       return f"{self.cart}_{self.product}"

apps/cart/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect
from .models import Cart, CartItem
# from django.views import View
#
# class CartView(View):
#    def get(selfself, request):
#       cart_items = CartItem.objects.filter(cart__user=request.user)
#       total_price = sum(item.product.price * item.quantity for item in cart_items)
#       context = {'cart_items': cart_items, 'total_price': total_price}
#       return render(request, 'cart.html', context)


def view_cart(request):
   cart_items = CartItem.objects.filter(cart__user=request.user)
   total_price = sum(item.product.price * item.quantity for item in cart_items)
   context = {'cart_items': cart_items, 'total_price': total_price}
   return render(request, 'cart/cart.html', context)


def update_item(request, item_id):
   item = CartItem.objects.get(id=item_id)
   item.quantity += int(request.GET.get('quantity'))
   item.save()
   return redirect('cart:view_cart')




def remove_item(request, item_id):
   CartItem.objects.filter(id=item_id).delete()
   return redirect('cart:view_cart')


def checkout(request):
   # code to handle checkout process
   return redirect('cart:view_cart')

apps/cart_shop/views.py
from django.views import View
from decimal import Decimal
from django.shortcuts import render, get_object_or_404, redirect
from .models import CartItemShop, Cart, Product
from apps.cart_shop.views import fill_card_in_session, fill_id_card_in_session

from rest_framework import viewsets, response
from rest_framework.permissions import IsAuthenticated
from .serializers import CartSerializer

class CartViewSet(viewsets.ModelViewSet):
    queryset = CartItemShop.objects.all()
    serializer_class = CartSerializer
    permission_classes = (IsAuthenticated,)

    def get_queryset(self):
        return self.queryset.filter(cart__user=self.request.user)

    def create(self, request, *args, **kwargs):
        cart_items = CartItemShop.objects.filter(cart__user=request.user,
                                                product__id=request.data.get('product'))
        if cart_items:
            cart_item = cart_items[0]
            if request.data.get('quantity'):
               cart_item.quantity += request.data.get('quantity')
            else:
               cart_item.quantity += 1
        else:
            product = get_object_or_404(Product, id=request.data.get('product'))
            cart_user = get_object_or_404(Cart, user=request.user)

            if request.data.get('quantity'):
                cart_item = CartItemShop(cart=cart_user, product=product, quantity=request.data.get('quantity'))
            else:
                cart_item = CartItemShop(cart=cart_user, product=product)
        cart_item.save()
        return response.Response({'message': 'Product added to cart'}, status=201)



    def fill_card_in_session(request):
        cart = request.session.get('cart', {})
        if request.user.is_authenticated and not cart:
            cart_items = CartItemShop.objects.filter(cart__user=request.user)
            for item in cart_items:
                cart[item.product.id] = item.quantity
            request.session['cart'] = cart
        return cart


    def fill_id_card_in_session(request):
        id_cart = request.session.get('id_cart', None)
        if request.user.is_authenticated and not id_cart:
            id_cart = Cart.objects.get(user=request.user).id
            request.session['id_cart'] = id_cart
        return id_cart

    def save_product_in_cart(request, product_id):
        cart = fill_card_in_session(request)

        if request.user.is_authenticated:
           cart_items = CartItemShop.objects.filter(cart__user=request.user,
                                                    product__id=product_id)
           if cart_items:
               cart_item = cart_items[0]
               cart_item.quantity += 1
           else:
               product = get_object_or_404(Product, id=product_id)
               cart_user = get_object_or_404(Cart, user=request.user)
               cart_item = CartItemShop(cart=cart_user, product=product)
           cart_item.save()
           cart[str(product_id)] = cart.get(str(product_id), 0) + 1
           request.session['cart'] = cart

    def update(self, request, *args, **kwargs):
        cart_item = get_object_or_404(CartItemShop, id=kwargs['pk'])
        if request.data.get('quantity'):
            cart_item.quantity = request.data['quantity']

        if request.data.get('product'):
            product = get_object_or_404(Product, id=request.data['product'])
            cart_item.product = product
            cart_item.save()
            return response.Response({'massage': 'Product change to cart'}, status=201)



class ViewCart(View):
    def get(self, request):
        cart = fill_card_in_session(request)
        if cart:
            products = Product.objects.filter(id__in=cart.keys())
            data = [{"product": product, "quantity": cart[str(product.id)], 'id': product.id} for product in products]
        else:
            data = []
        total_price_no_discount = sum(item['product'].price * item['quantity'] for item in data)
        if not total_price_no_discount:
            total_price_no_discount = Decimal("0.00")
        total_discount = sum(item['product'].price * item['product'].discount * item['quantity'] for item in data if item['product'].discount is not None) / 100
        if not total_discount:
            total_discount = Decimal("0.00")
        total_sum = total_price_no_discount - total_discount
        context = {'cart_items': data,
                   'total_price_no_discount': total_price_no_discount,
                   'total_discount': total_discount,
                   'total_sum': total_sum,
                   }
        return render(request, 'cart_shop/cart.html', context)

class ViewCartBuy(View):
    def get(self, request, product_id):
        save_product_in_cart(request, product_id)
        return redirect('cart_shop:cart')

# class ViewCartBuy(View):
#    def get(self, request, product_id):
#        product = get_object_or_404(Product, id=product_id)
#        cart_user = get_object_or_404(Cart, user=request.user)
#        cart_item = CartItemShop(cart=cart_user, product=product)
#        cart_item.save()


class ViewCartAdd(View):
   def get(self, request, product_id):
       save_product_in_cart(request, product_id)
       return redirect('home:index')

# class ViewCartAdd(View):
#    def get(self, request, product_id):
#        product = get_object_or_404(Product, id=product_id)
#        cart_user = get_object_or_404(Cart, user=request.user)
#        cart_item = CartItemShop(cart=cart_user, product=product)
#        cart_item.save()
#        return redirect('home:index')

class ViewCartDel(View):
   def get(self, request, item_id):
       cart = fill_card_in_session(request)
       cart_id = fill_id_card_in_session(request)
       if request.user.is_authenticated:
           cart_item = get_object_or_404(CartItemShop, cart__id=cart_id, product__id=item_id)
           cart_item.delete()
       cart.pop(str(item_id))
       request.session["cart"] = cart
       return redirect('cart_shop:cart')





   # def save_product_in_cart(request, product_id):
   #     product = get_object_or_404(Product, id=product_id)
   #     cart_user = get_object_or_404(Cart, user=request.user)
   #     cart_item = CartItemShop(cart=cart_user, product=product)
   #     cart_item.save()

   # def save_product_in_cart(request, product_id):
   #     cart_items = CartItemShop.objects.filter(cart__user=request.user,
   #                                              product__id=product_id)
   #     if cart_items:
   #         cart_item = cart_items[0]
   #         cart_item.quantity += 1
   #     else:
   #         product = get_object_or_404(Product, id=product_id)
   #     cart_user = get_object_or_404(Cart, user=request.user)
   #     cart_item = CartItemShop(cart=cart_user, product=product)
# class ViewWishListItem(View):
#     def get(self):
#         pass
#
# class ViewWishListAdd(View):
#     def get(self, request, product_id):
#         if request.user.is_authenticated:
#             wishlist_items =ViewWishListItem.object.filter(cart__user=request.user,product__id=product_id)
#             if wishlist_items:
#                 pass
#             else:
#                 product = get_object_or_404(Product, id=product_id)
#                 cart_user = get_object_or_404(Cart, user=request.user)
#                 wishlist_item = WishListItem(cart=cart_user, product=product)
#                 wishlist_item.save()
#             return redirect('home:index')
#         else:
#             return redirect('auth_shop:login')
#
# class ViewWishListDel(View):
#     def get(self, request, item_id):
#         product = get_object_or_404(Product, id=product_id)
#         cart_user = get_object_or_404(Cart, user=request.user)
#         wishlist_item = get_object_or_404(ViewWishListItem, id=item_id)
#         wishlist_item.delite()
#         return redirect('cart_shop:wishlist')

apps/wishlist/templates/cart_shop/wishlist.html
{% extends 'wishlist/base.html' %}
{% load static %}

{% block content %}


    <div class="hero-wrap hero-bread" style="background-image: url({% static 'shop/images/bg_1.jpg'%});">
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
          	<p class="breadcrumbs"><span class="mr-2"><a href="home/template/index.html">Home</a></span> <span>Wishlist</span></p>
            <h1 class="mb-0 bread">My Wishlist</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section ftco-cart">
			<div class="container">
				<div class="row">
    			<div class="col-md-12 ftco-animate">
    				<div class="cart-list">
	    				<table class="table">
						    <thead class="thead-primary">
						      <tr class="text-center">
						        <th>&nbsp;</th>
						        <th>Product List</th>
						        <th>&nbsp;</th>
						        <th>Price</th>
						        <th>Quantity</th>
						        <th>Total</th>
						      </tr>
						    </thead>
						    <tbody>
							{%for item in items%}


						      <tr class="text-center">
						        <td class="product-remove"><a href="{% url 'wishlist:del_from_wishlist' item.product.id%}"><span class="ion-ios-close"></span></a></td>
						        
						        <td class="image-prod"><div class="img" style="background-image:url({{item.product.image.url}});"></div></td>
						        
						        <td class="product-name">
						        	<h3>{{item.product.name}}</h3>
						        	<p>{{item.product.discription}}</p>
						        </td>
						        
						        <td class="price">${{item.product.price}}</td>
						        

						      </tr><!-- END TR-->
								{% endfor %}
						      <tr class="text-center">
						        <td class="product-remove"><a href="#"><span class="ion-ios-close"></span></a></td>
						        
						        <td class="image-prod"><div class="img" style="background-image:url(images/product-2.jpg);"></div></td>
						        
						        <td class="product-name">
						        	<h3>Bell Pepper</h3>
						        	<p>Far far away, behind the word mountains, far from the countries</p>
						        </td>
						        
						        <td class="price">$15.70</td>
						        
						        <td class="quantity">
						        	<div class="input-group mb-3">
					             	<input type="text" name="quantity" class="quantity form-control input-number" value="1" min="1" max="100">
					          	</div>
					          </td>
						        
						        <td class="total">$15.70</td>
						      </tr><!-- END TR-->

						      <tr class="text-center">
						        <td class="product-remove"><a href="#"><span class="ion-ios-close"></span></a></td>
						        
						        <td class="image-prod"><div class="img" style="background-image:url(images/product-3.jpg);"></div></td>
						        
						        <td class="product-name">
						        	<h3>Bell Pepper</h3>
						        	<p>Far far away, behind the word mountains, far from the countries</p>
						        </td>
						        
						        <td class="price">$15.70</td>
						        
						        <td class="quantity">
						        	<div class="input-group mb-3">
					             	<input type="text" name="quantity" class="quantity form-control input-number" value="1" min="1" max="100">
					          	</div>
					          </td>
						        
						        <td class="total">$15.70</td>
						      </tr><!-- END TR-->

						      <tr class="text-center">
						        <td class="product-remove"><a href="#"><span class="ion-ios-close"></span></a></td>
						        
						        <td class="image-prod"><div class="img" style="background-image:url(images/product-4.jpg);"></div></td>
						        
						        <td class="product-name">
						        	<h3>Bell Pepper</h3>
						        	<p>Far far away, behind the word mountains, far from the countries</p>
						        </td>
						        
						        <td class="price">$15.70</td>
						        
						        <td class="quantity">
						        	<div class="input-group mb-3">
					             	<input type="text" name="quantity" class="quantity form-control input-number" value="1" min="1" max="100">
					          	</div>
					          </td>
						        
						        <td class="total">$15.70</td>
						      </tr><!-- END TR-->

						      <tr class="text-center">
						        <td class="product-remove"><a href="#"><span class="ion-ios-close"></span></a></td>
						        
						        <td class="image-prod"><div class="img" style="background-image:url(images/product-5.jpg);"></div></td>
						        
						        <td class="product-name">
						        	<h3>Bell Pepper</h3>
						        	<p>Far far away, behind the word mountains, far from the countries</p>
						        </td>
						        
						        <td class="price">$15.70</td>
						        
						        <td class="quantity">
						        	<div class="input-group mb-3">
					             	<input type="text" name="quantity" class="quantity form-control input-number" value="1" min="1" max="100">
					          	</div>
					          </td>
						        
						        <td class="total">$15.70</td>
						      </tr><!-- END TR-->

						      <tr class="text-center">
						        <td class="product-remove"><a href="#"><span class="ion-ios-close"></span></a></td>
						        
						        <td class="image-prod"><div class="img" style="background-image:url(images/product-6.jpg);"></div></td>
						        
						        <td class="product-name">
						        	<h3>Bell Pepper</h3>
						        	<p>Far far away, behind the word mountains, far from the countries</p>
						        </td>
						        
						        <td class="price">$15.70</td>
						        
						        <td class="quantity">
						        	<div class="input-group mb-3">
					             	<input type="text" name="quantity" class="quantity form-control input-number" value="1" min="1" max="100">
					          	</div>
					          </td>
						        
						        <td class="total">$15.70</td>
						      </tr><!-- END TR-->
						    </tbody>
						  </table>
					  </div>
    			</div>
    		</div>
			</div>
		</section>

		<section class="ftco-section ftco-no-pt ftco-no-pb py-5 bg-light">
      <div class="container py-4">
        <div class="row d-flex justify-content-center py-5">
          <div class="col-md-6">
          	<h2 style="font-size: 22px;" class="mb-0">Subcribe to our Newsletter</h2>
          	<span>Get e-mail updates about our latest shops and special offers</span>
          </div>
          <div class="col-md-6 d-flex align-items-center">
            <form action="#" class="subscribe-form">
              <div class="form-group d-flex">
                <input type="text" class="form-control" placeholder="Enter email address">
                <input type="submit" value="Subscribe" class="submit px-3">
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>
    <footer class="ftco-footer ftco-section">
      <div class="container">
      	<div class="row">
      		<div class="mouse">
						<a href="#" class="mouse-icon">
							<div class="mouse-wheel"><span class="ion-ios-arrow-up"></span></div>
						</a>
					</div>
      	</div>
        <div class="row mb-5">
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Vegefoods</h2>
              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia.</p>
              <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4 ml-md-5">
              <h2 class="ftco-heading-2">Menu</h2>
              <ul class="list-unstyled">
                <li><a href="#" class="py-2 d-block">Shop</a></li>
                <li><a href="#" class="py-2 d-block">About</a></li>
                <li><a href="#" class="py-2 d-block">Journal</a></li>
                <li><a href="#" class="py-2 d-block">Contact Us</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-4">
             <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Help</h2>
              <div class="d-flex">
	              <ul class="list-unstyled mr-l-5 pr-l-3 mr-4">
	                <li><a href="#" class="py-2 d-block">Shipping Information</a></li>
	                <li><a href="#" class="py-2 d-block">Returns &amp; Exchange</a></li>
	                <li><a href="#" class="py-2 d-block">Terms &amp; Conditions</a></li>
	                <li><a href="#" class="py-2 d-block">Privacy Policy</a></li>
	              </ul>
	              <ul class="list-unstyled">
	                <li><a href="#" class="py-2 d-block">FAQs</a></li>
	                <li><a href="#" class="py-2 d-block">Contact</a></li>
	              </ul>
	            </div>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
            	<h2 class="ftco-heading-2">Have a Questions?</h2>
            	<div class="block-23 mb-3">
	              <ul>
	                <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span></li>
	                <li><a href="#"><span class="icon icon-phone"></span><span class="text">+2 392 3929 210</span></a></li>
	                <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a></li>
	              </ul>
	            </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-center">

            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
						  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						</p>
          </div>
        </div>
      </div>
    </footer>
    
  

  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


  <script src="js/jquery.min.js"></script>
  <script src="js/jquery-migrate-3.0.1.min.js"></script>
  <script src="js/popper.min.js"></script>
  <script src="js/bootstrap.min.js"></script>
  <script src="js/jquery.easing.1.3.js"></script>
  <script src="js/jquery.waypoints.min.js"></script>
  <script src="js/jquery.stellar.min.js"></script>
  <script src="js/owl.carousel.min.js"></script>
  <script src="js/jquery.magnific-popup.min.js"></script>
  <script src="js/aos.js"></script>
  <script src="js/jquery.animateNumber.min.js"></script>
  <script src="js/bootstrap-datepicker.js"></script>
  <script src="js/scrollax.min.js"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="js/google-map.js"></script>
  <script src="js/main.js"></script>

  <script>
		$(document).ready(function(){

		var quantitiy=0;
		   $('.quantity-right-plus').click(function(e){
		        
		        // Stop acting like a button
		        e.preventDefault();
		        // Get the field name
		        var quantity = parseInt($('#quantity').val());
		        
		        // If is not undefined
		            
		            $('#quantity').val(quantity + 1);

		          
		            // Increment
		        
		    });

		     $('.quantity-left-minus').click(function(e){
		        // Stop acting like a button
		        e.preventDefault();
		        // Get the field name
		        var quantity = parseInt($('#quantity').val());
		        
		        // If is not undefined
		      
		            // Increment
		            if(quantity>0){
		            $('#quantity').val(quantity - 1);
		            }
		    });
		    
		});
	</script>
    
  </body>
</html>